# Generated by Django 3.1.4 on 2020-12-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerimage',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='%Y/%m/%d'),
        ),
    ]
