# Generated by Django 3.1.4 on 2020-12-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_headerimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerimage',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='headerimage',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='Mainslider'),
        ),
    ]
