# Generated by Django 3.1.4 on 2020-12-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20201221_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('image', models.ImageField(default=None, null=True, upload_to='services')),
                ('description', models.TextField()),
                ('services_url', models.URLField(default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='headerimage',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
