# Generated by Django 3.1.4 on 2020-12-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20201221_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('logo', models.ImageField(default=None, null=True, upload_to='testimonial')),
            ],
        ),
        migrations.AlterField(
            model_name='headerimage',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
